insert into person (ID, Name, lastName, Age, Gender, Location) values (0,'Felipe','Ramírez Parra',51,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (1,'Matías','Rincón Valencia',20,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (2,'Santiago','Vargas Rincón',30,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (3,'Jerónimo','Medina Romero',70,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (4,'Felipe','Gómez Valencia',29,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (5,'Maximiliano','Muñoz Jaramillo',52,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (6,'Santiago','Ortiz Romero',7,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (7,'Emiliano','Jaramillo Salazar',39,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (8,'Martín','Muñoz Herrera',16,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (9,'Samuel','Romero López',60,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (10,'Mathias','Castro Muñoz',26,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (11,'Andres','Cárdenas Escobar',10,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (12,'Andres','Castro Zapata',67,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (13,'Emiliano','Parra Salazar',27,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (14,'Felipe','Valencia Arias',25,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (15,'Felipe','Medina Valencia',32,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (16,'Jerónimo','Restrepo Jiménez',4,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (17,'Matías','Ramírez Hernández',23,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (18,'Thiago','Díaz Arias',11,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (19,'Andres','García Jaramillo',34,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (20,'Andres','Álvarez Herrera',45,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (21,'Andres','López Romero',67,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (22,'Jerónimo','Álvarez Ortiz',24,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (23,'Felipe','Medina Rincón',66,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (24,'Andres','Cárdenas Hernández',18,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (25,'Jerónimo','Díaz Cardona',37,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (26,'Samuel','Díaz Medina',14,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (27,'Samuel','Martínez Escobar',23,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (28,'Emiliano','Martínez Valencia',14,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (29,'Emiliano','Medina Rodríguez',22,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (30,'Maximiliano','Romero Álvarez',57,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (31,'Maximiliano','Medina Rivera',68,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (32,'Maximiliano','Correa Escobar',5,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (33,'Matías','González Correa',77,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (34,'Martín','Castillo Mejía',54,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (35,'Andres','Hernández Díaz',69,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (36,'Mathias','González Álvarez',13,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (37,'Emiliano','Flórez Herrera',34,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (38,'Emiliano','Flórez Díaz',8,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (39,'Thiago','González Sánchez',9,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (40,'Maximiliano','Herrera Parra',4,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (41,'Andres','Jaramillo Montoya',34,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (42,'Thiago','Flórez Cardona',19,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (43,'Thiago','Hernández Montoya',46,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (44,'Maximiliano','Álvarez Cortes',1,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (45,'Jerónimo','Quintero Gómez',4,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (46,'Jerónimo','Medina Quintero',23,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (47,'Emmanuel','Giraldo Martínez',72,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (48,'Martín','García Ruiz',3,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (49,'Andres','Mejía López',53,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (50,'Felipe','Álvarez Cardona',31,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (51,'Thiago','Flórez González',19,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (52,'Thiago','Vargas Rincón',2,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (53,'Emmanuel','Montoya Rivera',74,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (54,'Emmanuel','Cardona Ramírez',77,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (55,'Maximiliano','Osorio Herrera',64,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (56,'Thiago','Montoya Ortiz',40,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (57,'Thiago','Flórez Marín',61,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (58,'Samuel','Escobar Rodríguez',32,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (59,'Samuel','Giraldo Ruiz',52,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (60,'Andres','Rodríguez Flórez',61,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (61,'Jerónimo','Cortes Moreno',66,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (62,'Martín','Salazar Muñoz',25,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (63,'Maximiliano','Rincón Muñoz',62,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (64,'Santiago','Jiménez Castillo',32,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (65,'Jerónimo','Muñoz González',53,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (66,'Maximiliano','Álvarez Muñoz',25,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (67,'Emmanuel','Vargas Parra',6,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (68,'Emmanuel','Cárdenas Parra',50,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (69,'Maximiliano','Jaramillo Cardona',69,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (70,'Emiliano','Gutiérrez Jaramillo',44,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (71,'Emmanuel','Castro Díaz',4,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (72,'Emiliano','Suárez Gómez',67,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (73,'Thiago','Valencia Montoya',31,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (74,'Emmanuel','Flórez Gutiérrez',41,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (75,'Mathias','Osorio Torres',38,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (76,'Maximiliano','Marín Suárez',55,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (77,'Matías','Correa Suárez',52,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (78,'Maximiliano','Marín Ramírez',51,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (79,'Emiliano','Rivera Zapata',78,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (80,'Santiago','Álvarez Arias',42,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (81,'Maximiliano','Sánchez Cárdenas',2,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (82,'Santiago','González Ortiz',48,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (83,'Maximiliano','Vargas Valencia',30,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (84,'Mathias','Cardona Valencia',74,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (85,'Martín','Martínez Suárez',56,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (86,'Emiliano','Díaz Valencia',80,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (87,'Samuel','Jiménez Ruiz',51,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (88,'Felipe','Rincón Quintero',25,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (89,'Samuel','Sánchez Castro',47,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (90,'Felipe','Álvarez Gómez',45,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (91,'Mathias','Sánchez Jiménez',41,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (92,'Samuel','García Vargas',8,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (93,'Martín','López Montoya',65,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (94,'Santiago','Salazar Montoya',55,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (95,'Maximiliano','Gutiérrez Morales',22,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (96,'Jerónimo','Montoya Parra',22,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (97,'Emmanuel','Herrera Castillo',4,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (98,'Jerónimo','Gutiérrez Moreno',20,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (99,'Emiliano','Quintero Escobar',29,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (100,'Matías','Ortiz Velásquez',50,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (101,'Thiago','Morales Salazar',17,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (102,'Maximiliano','Valencia Jiménez',17,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (103,'Samuel','Flórez Suárez',2,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (104,'Maximiliano','Castillo Hernández',70,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (105,'Felipe','Moreno Castillo',41,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (106,'Samuel','Herrera Castro',62,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (107,'Emiliano','Escobar Castillo',23,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (108,'Felipe','Vargas González',73,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (109,'Matías','Romero Rincón',30,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (110,'Andres','Salazar Rojas',58,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (111,'Jerónimo','Restrepo Correa',60,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (112,'Thiago','Giraldo Medina',6,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (113,'Santiago','Álvarez Suárez',72,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (114,'Thiago','Montoya Díaz',53,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (115,'Emmanuel','Muñoz Álvarez',35,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (116,'Matías','Torres Martínez',47,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (117,'Felipe','Sánchez Vargas',3,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (118,'Emiliano','Giraldo Restrepo',6,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (119,'Maximiliano','Cardona Velásquez',69,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (120,'Maximiliano','Restrepo Sánchez',65,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (121,'Mathias','Gómez Medina',77,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (122,'Martín','Mejía Cortes',76,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (123,'Matías','Herrera Moreno',20,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (124,'Felipe','Herrera Quintero',50,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (125,'Santiago','Parra Sánchez',12,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (126,'Martín','Cardona Muñoz',0,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (127,'Andres','Vargas Castro',44,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (128,'Matías','Suárez Mejía',35,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (129,'Emmanuel','Arias Jiménez',62,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (130,'Emmanuel','Jiménez Valencia',11,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (131,'Martín','Hernández Castro',22,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (132,'Mathias','Sánchez Pérez',3,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (133,'Matías','Rojas Rivera',0,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (134,'Andres','Arias Muñoz',58,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (135,'Emiliano','Valencia Álvarez',66,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (136,'Santiago','Zapata Escobar',35,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (137,'Mathias','Giraldo Torres',18,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (138,'Emmanuel','Vargas Escobar',52,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (139,'Andres','Romero López',14,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (140,'Emmanuel','Hernández Rodríguez',45,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (141,'Emmanuel','Salazar Cardona',10,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (142,'Martín','Rodríguez Restrepo',15,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (143,'Felipe','Rincón García',24,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (144,'Emmanuel','Moreno Suárez',56,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (145,'Thiago','Montoya Valencia',6,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (146,'Santiago','Valencia Velásquez',22,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (147,'Samuel','Pérez Moreno',48,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (148,'Felipe','Rivera Rivera',59,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (149,'Matías','Flórez López',60,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (150,'Martín','Medina Díaz',65,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (151,'Samuel','Salazar Herrera',17,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (152,'Emiliano','Arias Ortiz',1,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (153,'Emmanuel','Díaz Giraldo',48,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (154,'Andres','Castillo Ruiz',14,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (155,'Martín','Ortiz Medina',29,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (156,'Felipe','Díaz Parra',44,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (157,'Maximiliano','Ruiz Castro',12,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (158,'Felipe','Rodríguez Arias',40,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (159,'Matías','Correa Flórez',56,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (160,'Matías','Quintero Jaramillo',35,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (161,'Santiago','Jiménez Zapata',47,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (162,'Maximiliano','Sánchez Medina',54,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (163,'Martín','Jaramillo Castillo',35,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (164,'Felipe','Arias Restrepo',41,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (165,'Emiliano','Escobar Parra',74,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (166,'Jerónimo','Valencia Gutiérrez',56,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (167,'Felipe','Sánchez Cortes',1,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (168,'Mathias','Velásquez Suárez',76,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (169,'Thiago','Moreno Rivera',69,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (170,'Emmanuel','Rodríguez Rojas',68,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (171,'Samuel','Moreno Castro',15,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (172,'Santiago','Flórez Hernández',4,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (173,'Felipe','Cárdenas Rodríguez',78,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (174,'Martín','Morales Velásquez',42,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (175,'Mathias','Zapata Cárdenas',69,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (176,'Andres','Cortes Zapata',2,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (177,'Emiliano','Arias Medina',37,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (178,'Emiliano','Mejía Rodríguez',5,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (179,'Emiliano','Restrepo Hernández',20,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (180,'Martín','Martínez Cardona',27,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (181,'Samuel','Restrepo Escobar',3,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (182,'Matías','Restrepo Escobar',28,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (183,'Samuel','Suárez Montoya',2,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (184,'Thiago','Parra Velásquez',76,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (185,'Emmanuel','García Osorio',69,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (186,'Samuel','Correa Jiménez',80,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (187,'Emmanuel','Arias Escobar',53,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (188,'Felipe','Castro Restrepo',61,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (189,'Emmanuel','Gutiérrez Ruiz',76,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (190,'Emiliano','Ramírez Cardona',41,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (191,'Samuel','Mejía Cortes',57,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (192,'Emmanuel','Rodríguez Osorio',67,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (193,'Andres','Morales Medina',75,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (194,'Felipe','Parra Ramírez',63,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (195,'Martín','Hernández García',32,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (196,'Maximiliano','López Martínez',21,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (197,'Matías','Medina Jaramillo',10,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (198,'Emmanuel','Álvarez Pérez',21,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (199,'Emiliano','Ramírez Salazar',64,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (200,'Martín','González Salazar',39,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (201,'Emmanuel','Vargas Medina',80,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (202,'Maximiliano','Valencia Vargas',35,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (203,'Felipe','Salazar Moreno',13,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (204,'Thiago','Gómez Zapata',61,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (205,'Jerónimo','Velásquez Marín',47,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (206,'Felipe','Rivera Marín',47,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (207,'Mathias','Cortes Escobar',62,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (208,'Thiago','Montoya Herrera',76,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (209,'Martín','López López',44,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (210,'Andres','Zapata Flórez',43,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (211,'Thiago','Zapata Pérez',68,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (212,'Andres','Restrepo Rojas',40,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (213,'Maximiliano','Herrera Cortes',69,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (214,'Felipe','Muñoz Restrepo',75,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (215,'Samuel','Hernández García',20,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (216,'Samuel','Restrepo Giraldo',18,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (217,'Emmanuel','Hernández García',14,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (218,'Andres','Quintero Torres',68,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (219,'Emiliano','Quintero Salazar',58,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (220,'Felipe','Romero Marín',26,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (221,'Matías','Díaz Rincón',52,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (222,'Thiago','Álvarez López',29,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (223,'Maximiliano','Salazar Rojas',69,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (224,'Santiago','Escobar Osorio',53,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (225,'Felipe','Velásquez Álvarez',41,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (226,'Maximiliano','Vargas Velásquez',67,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (227,'Andres','Vargas Restrepo',45,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (228,'Jerónimo','Sánchez Medina',7,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (229,'Emiliano','Mejía Moreno',17,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (230,'Emiliano','Sánchez Álvarez',53,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (231,'Felipe','Jaramillo Hernández',39,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (232,'Andres','Morales Hernández',46,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (233,'Samuel','Romero Giraldo',41,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (234,'Thiago','Castro Jiménez',42,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (235,'Emiliano','Herrera Medina',28,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (236,'Samuel','Díaz Arias',43,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (237,'Jerónimo','Rivera Torres',7,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (238,'Maximiliano','Torres Arias',19,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (239,'Jerónimo','Parra Díaz',75,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (240,'Martín','Cortes Suárez',64,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (241,'Maximiliano','Rodríguez Zapata',16,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (242,'Emiliano','Parra Cárdenas',58,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (243,'Emiliano','Jaramillo Cárdenas',49,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (244,'Emmanuel','Cárdenas Díaz',47,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (245,'Felipe','Jiménez Mejía',63,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (246,'Thiago','Mejía López',46,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (247,'Santiago','Herrera Romero',34,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (248,'Martín','Escobar Gutiérrez',48,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (249,'Matías','Zapata Hernández',23,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (250,'Felipe','Rivera Cardona',11,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (251,'Andres','Ruiz Muñoz',23,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (252,'Andres','Muñoz Jiménez',34,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (253,'Thiago','Vargas Flórez',13,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (254,'Mathias','Flórez Martínez',28,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (255,'Santiago','Jaramillo Rincón',71,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (256,'Emmanuel','Gómez Medina',41,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (257,'Thiago','Díaz Rodríguez',64,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (258,'Santiago','Mejía Hernández',33,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (259,'Matías','Parra Hernández',1,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (260,'Santiago','Pérez Arias',36,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (261,'Mathias','Cortes Ruiz',75,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (262,'Felipe','Giraldo Sánchez',49,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (263,'Martín','Hernández Correa',64,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (264,'Emmanuel','Rojas Marín',20,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (265,'Emiliano','Sánchez Parra',77,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (266,'Thiago','Pérez Martínez',31,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (267,'Maximiliano','Cortes Rojas',25,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (268,'Emmanuel','Valencia Morales',2,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (269,'Martín','Gutiérrez Álvarez',12,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (270,'Thiago','Jaramillo Romero',8,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (271,'Emiliano','Cardona López',21,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (272,'Mathias','Cardona Vargas',72,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (273,'Emiliano','Gómez González',79,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (274,'Matías','Arias Romero',28,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (275,'Andres','Morales Flórez',10,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (276,'Thiago','Hernández Velásquez',54,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (277,'Jerónimo','Medina Hernández',21,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (278,'Martín','Escobar Sánchez',70,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (279,'Felipe','Mejía Álvarez',71,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (280,'Andres','Giraldo Castillo',66,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (281,'Felipe','Ramírez Rojas',42,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (282,'Samuel','Martínez Escobar',52,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (283,'Thiago','Rincón Restrepo',80,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (284,'Thiago','Osorio Flórez',72,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (285,'Matías','Herrera Torres',60,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (286,'Thiago','Correa Pérez',11,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (287,'Felipe','Hernández Hernández',11,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (288,'Samuel','Castro Cortes',44,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (289,'Jerónimo','Gómez Giraldo',21,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (290,'Samuel','Rincón Romero',5,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (291,'Santiago','Morales Flórez',28,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (292,'Thiago','Rivera Hernández',45,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (293,'Andres','Romero Velásquez',24,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (294,'Emiliano','Giraldo Morales',56,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (295,'Jerónimo','López Ruiz',14,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (296,'Matías','Mejía Rodríguez',67,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (297,'Emmanuel','Vargas Herrera',31,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (298,'Santiago','Valencia Muñoz',18,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (299,'Emmanuel','Torres Herrera',8,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (300,'Matías','Valencia Herrera',17,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (301,'Martín','Romero González',33,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (302,'Samuel','Restrepo Osorio',11,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (303,'Emmanuel','Torres Cardona',40,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (304,'Mathias','Muñoz Salazar',76,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (305,'Martín','Cortes Hernández',34,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (306,'Felipe','Cárdenas Castillo',29,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (307,'Maximiliano','Valencia Restrepo',79,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (308,'Maximiliano','Torres Cardona',60,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (309,'Samuel','Ortiz Sánchez',13,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (310,'Andres','Muñoz Rodríguez',35,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (311,'Jerónimo','Álvarez Gutiérrez',78,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (312,'Samuel','Gómez Sánchez',17,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (313,'Felipe','Correa Rincón',0,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (314,'Martín','Suárez Velásquez',44,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (315,'Thiago','López Cardona',71,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (316,'Felipe','Martínez Ramírez',64,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (317,'Felipe','Martínez Quintero',35,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (318,'Thiago','Sánchez Jiménez',11,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (319,'Emiliano','García Quintero',6,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (320,'Samuel','Medina Hernández',17,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (321,'Emmanuel','Castro Pérez',80,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (322,'Emiliano','Suárez Flórez',29,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (323,'Jerónimo','Giraldo Marín',71,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (324,'Andres','Ruiz López',24,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (325,'Jerónimo','Hernández Cortes',72,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (326,'Andres','Escobar Morales',40,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (327,'Emmanuel','Rincón Ortiz',55,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (328,'Emiliano','Rincón Torres',77,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (329,'Santiago','Castillo Valencia',1,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (330,'Emmanuel','Sánchez Rivera',58,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (331,'Felipe','Hernández Ortiz',3,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (332,'Maximiliano','Marín Marín',39,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (333,'Samuel','Parra Romero',14,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (334,'Thiago','García Restrepo',63,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (335,'Felipe','Muñoz García',22,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (336,'Maximiliano','Martínez Herrera',72,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (337,'Maximiliano','Jiménez Rincón',12,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (338,'Santiago','Cortes Flórez',44,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (339,'Mathias','Cárdenas Osorio',6,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (340,'Mathias','Mejía Arias',15,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (341,'Emmanuel','Gutiérrez Restrepo',77,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (342,'Andres','Martínez Castillo',62,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (343,'Emmanuel','Cortes Hernández',42,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (344,'Jerónimo','Arias Parra',25,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (345,'Felipe','Romero Jiménez',60,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (346,'Felipe','Ortiz Torres',43,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (347,'Martín','Marín Velásquez',79,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (348,'Emmanuel','González López',25,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (349,'Maximiliano','Morales Valencia',10,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (350,'Martín','Giraldo Martínez',16,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (351,'Mathias','Pérez Zapata',72,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (352,'Martín','González Restrepo',68,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (353,'Martín','Ramírez Rodríguez',41,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (354,'Felipe','Vargas Rodríguez',44,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (355,'Santiago','Valencia Valencia',8,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (356,'Jerónimo','Vargas Marín',14,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (357,'Thiago','Cortes Restrepo',49,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (358,'Emmanuel','Velásquez Cardona',5,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (359,'Matías','Moreno Zapata',64,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (360,'Samuel','Salazar Romero',72,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (361,'Maximiliano','Vargas Romero',61,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (362,'Matías','Mejía Arias',27,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (363,'Andres','Arias Zapata',51,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (364,'Felipe','Flórez Flórez',46,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (365,'Maximiliano','Vargas Sánchez',72,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (366,'Maximiliano','Velásquez Parra',7,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (367,'Andres','Herrera Suárez',13,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (368,'Maximiliano','Giraldo Quintero',71,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (369,'Emiliano','Romero Parra',31,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (370,'Mathias','López Moreno',77,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (371,'Emiliano','Velásquez Restrepo',5,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (372,'Emiliano','Rodríguez Torres',1,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (373,'Thiago','Morales Álvarez',45,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (374,'Martín','Castro Correa',51,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (375,'Maximiliano','Torres Morales',55,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (376,'Samuel','Hernández Castillo',65,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (377,'Emmanuel','Parra Giraldo',69,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (378,'Santiago','Muñoz Díaz',35,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (379,'Mathias','Osorio Sánchez',42,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (380,'Andres','Gutiérrez Velásquez',16,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (381,'Jerónimo','Vargas Gómez',29,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (382,'Martín','Flórez Rojas',49,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (383,'Thiago','Castro Parra',27,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (384,'Mathias','Rodríguez Restrepo',24,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (385,'Matías','Hernández Romero',33,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (386,'Emmanuel','García Torres',66,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (387,'Santiago','Rojas Valencia',8,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (388,'Emmanuel','Rincón Muñoz',23,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (389,'Santiago','Romero Correa',47,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (390,'Felipe','Mejía Rivera',44,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (391,'Andres','Zapata Rojas',33,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (392,'Martín','Jaramillo Díaz',13,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (393,'Matías','Muñoz Vargas',0,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (394,'Emiliano','Osorio Cardona',7,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (395,'Matías','Moreno Jiménez',66,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (396,'Samuel','Jiménez García',70,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (397,'Martín','Herrera Hernández',39,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (398,'Felipe','Morales Muñoz',27,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (399,'Emiliano','Rojas Velásquez',60,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (400,'Mathias','Restrepo Jiménez',45,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (401,'Maximiliano','Díaz Osorio',17,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (402,'Emiliano','Ruiz Vargas',8,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (403,'Thiago','Gutiérrez Herrera',6,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (404,'Samuel','Cárdenas Ortiz',66,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (405,'Emiliano','Romero Sánchez',8,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (406,'Felipe','Torres Suárez',71,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (407,'Samuel','Parra Medina',55,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (408,'Felipe','Rincón Muñoz',32,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (409,'Santiago','Osorio Restrepo',69,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (410,'Jerónimo','Marín Martínez',73,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (411,'Thiago','Castro Suárez',73,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (412,'Matías','Castillo Cortes',43,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (413,'Emmanuel','Castillo Jaramillo',80,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (414,'Matías','Ruiz Martínez',64,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (415,'Martín','Álvarez Correa',32,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (416,'Emmanuel','Hernández Rodríguez',19,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (417,'Martín','Gutiérrez Rodríguez',72,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (418,'Emiliano','Cardona Osorio',42,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (419,'Jerónimo','Rodríguez Velásquez',45,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (420,'Matías','Díaz Flórez',59,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (421,'Martín','Hernández Suárez',41,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (422,'Felipe','Martínez Ruiz',19,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (423,'Mathias','Medina Morales',57,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (424,'Emmanuel','Díaz Torres',28,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (425,'Jerónimo','Muñoz Medina',69,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (426,'Mathias','Rivera Rojas',31,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (427,'Martín','Hernández Álvarez',14,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (428,'Martín','Rincón Medina',24,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (429,'Jerónimo','Rodríguez Muñoz',3,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (430,'Matías','Medina Castro',25,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (431,'Felipe','Rincón Quintero',58,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (432,'Emmanuel','Rojas García',33,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (433,'Jerónimo','Arias Rodríguez',42,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (434,'Felipe','Restrepo Muñoz',64,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (435,'Samuel','Díaz González',44,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (436,'Andres','Sánchez Castro',79,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (437,'Jerónimo','Jiménez Restrepo',18,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (438,'Andres','Castro Cortes',42,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (439,'Matías','Arias Hernández',61,'M','Guática');
insert into person (ID, Name, lastName, Age, Gender, Location) values (440,'Mathias','Arias Díaz',13,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (441,'Thiago','Castro Escobar',23,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (442,'Maximiliano','Pérez Cortes',24,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (443,'Mathias','Pérez Jaramillo',17,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (444,'Samuel','Escobar Torres',54,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (445,'Mathias','Ortiz Quintero',53,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (446,'Jerónimo','Sánchez Hernández',5,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (447,'Felipe','Díaz Herrera',13,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (448,'Emiliano','Pérez Valencia',22,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (449,'Felipe','Romero Salazar',53,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (450,'Matías','Ortiz Parra',11,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (451,'Mathias','Morales Suárez',78,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (452,'Mathias','González Cardona',46,'M','Santa rosa de cabal');
insert into person (ID, Name, lastName, Age, Gender, Location) values (453,'Santiago','Muñoz Gutiérrez',3,'M','Santa marta');
insert into person (ID, Name, lastName, Age, Gender, Location) values (454,'Emiliano','Arias Velásquez',15,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (455,'Matías','Ortiz Escobar',38,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (456,'Samuel','Torres Romero',11,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (457,'Santiago','Cardona Osorio',33,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (458,'Samuel','Hernández Rivera',63,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (459,'Thiago','Moreno Restrepo',65,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (460,'Thiago','Sánchez Giraldo',51,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (461,'Thiago','Ruiz Hernández',29,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (462,'Emiliano','Cárdenas Hernández',5,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (463,'Jerónimo','Quintero Cortes',64,'M','Bogotá');
insert into person (ID, Name, lastName, Age, Gender, Location) values (464,'Santiago','Velásquez Rivera',55,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (465,'Maximiliano','Parra Díaz',26,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (466,'Thiago','Suárez Escobar',6,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (467,'Thiago','Osorio González',34,'M','Arauca');
insert into person (ID, Name, lastName, Age, Gender, Location) values (468,'Emmanuel','Rivera Osorio',14,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (469,'Felipe','Gómez Díaz',1,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (470,'Andres','Castro Medina',5,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (471,'Samuel','Hernández López',35,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (472,'Thiago','Suárez Ruiz',0,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (473,'Matías','Jiménez Rojas',57,'M','Medellín');
insert into person (ID, Name, lastName, Age, Gender, Location) values (474,'Emmanuel','Cardona Osorio',46,'M','Viterbo');
insert into person (ID, Name, lastName, Age, Gender, Location) values (475,'Emmanuel','Correa Giraldo',18,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (476,'Maximiliano','Moreno Mejía',54,'M','Riosucio');
insert into person (ID, Name, lastName, Age, Gender, Location) values (477,'Jerónimo','Suárez Cardona',8,'M','Cartagena');
insert into person (ID, Name, lastName, Age, Gender, Location) values (478,'Andres','Rodríguez Álvarez',34,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (479,'Jerónimo','Álvarez Correa',22,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (480,'Matías','Flórez Escobar',65,'M','Pereira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (481,'Emiliano','Muñoz Romero',28,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (482,'Samuel','Valencia Cárdenas',49,'M','Pácora');
insert into person (ID, Name, lastName, Age, Gender, Location) values (483,'Maximiliano','Mejía Pérez',14,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (484,'Emiliano','Romero Hernández',26,'M','Manizales');
insert into person (ID, Name, lastName, Age, Gender, Location) values (485,'Emmanuel','Marín Cardona',42,'M','Barranquilla');
insert into person (ID, Name, lastName, Age, Gender, Location) values (486,'Thiago','Hernández Gutiérrez',38,'M','Palmira');
insert into person (ID, Name, lastName, Age, Gender, Location) values (487,'Emmanuel','Pérez Jaramillo',3,'M','Anserma');
insert into person (ID, Name, lastName, Age, Gender, Location) values (488,'Andres','Ramírez Pérez',24,'M','Cali');
insert into person (ID, Name, lastName, Age, Gender, Location) values (489,'Emiliano','Restrepo Salazar',68,'M','Santa marta');
